---
title: 'Dealing with Consumer Uncertainty: Online Product Reviews and What makes them helpful?'
bibliography: references.bib
link-citations: yes
csl: ieee.csl
---

# Introduction

Online shopping has becoming more and more prevalent in average consumer's daily life. Electronic shopping brought many advantages both for sellers and buyers. One of the positive perks is Online Customer Reviews (OCR). Online Customer Reviews come in the form of electronic word-of-mouth @dellarocas2003 and can be defined as "*peer-generated product evaluations posted on company or third party websites*" @mudambi2010. OCR have an effect on product sales as well as consumer decision making [@duan2008; @lee2011]. \###(need different citations here!!!)\###

OCR help customers by decreasing their search costs. Customers try to get information on the product they are going to buy so that they can decrease the uncertainty about that particular product. This information acquiring process is costly. Furthermore, this information gathering process might be more or less costly depending on the product type, namely Search and Experience goods \@10.2307/1830691. Search goods, by nature, have traits that can be observed objectively before buying (GHz of a CPU of a Laptop). On the other hand, quality of Experience goods can't be evaluated before buying and evaluations could be very subjective (One needs to watch a movie in order to understand if it is a good movie or not.).

However, the increased rate of electronic commerce activity also created an abundance of product reviews on the internet. The vast amount of product reviews might increase the information overload on the customer [@sun2019; @fan2021]. Unfortunately, this information overload can make the search process even costlier because it is really time consuming to evaluate thousand of customer reviews. Additionally, not all reviews have the same informativeness level @pan2011. Therefore, answering the question of "what makes a helpful review?" is very important because reading more and more reviews can only increase the search cost. To make the understanding of a "helpful review" more clear we can define them as "*a peer-generated product evaluation that facilitates the consumer's purchase decision process*" @mudambi2010.

Since OCR don't share the same level of informativeness and usefulness @pan2011, most of the electronic retail websites implemented a very well known "helpfulness" feature to their customer review systems in order to help their customers navigate through thousand of reviews. On some websites, this feature is implemented in a way that helpful / unhelpful buttons are present and on some other websites, there is only a helpful button. In this paper, we acquired data from websites which support helpful / unhelpful system since it was found that helpfulness as a percentage (helpful votes over total votes) creates more powerful results than considering only helpful votes as a count variable @ahmad2015.

The research on perceived helpfulness is still growing. In Social and Behavioral Sciences, it is common to have conflicting papers and results in the literature @hunter1991. In this case, the study on perceived helpfulness is not an exception. Because of this reason, We think more empirical studies on perceived helpfulness are required. This paper aims to add one more perspective to growing literature of customer reviews and review helpfulness.

-   Briefly talk about other research papers and present the data.

-   Briefly talk about the results.

-   Outline the paper

# Literature Review

-   mention moderating effects of product type for every variable

The research on Online Customer Reviews could be considered to have two main branches. One branch is heavily marketing oriented and tries to understand the effects of OCR on sales [@ghose2011; @ögüt2012]. The other branch is concerned with rather behavioral or psychological outcomes and focuses on perceived helpfulness only. Of course, the boundary between these two branches are somewhat blurry and same independent variables were used to explain both helpfulness and sales. Furthermore, @topaloglu2019 found that helpfulness have a moderating effect on sales. Many other papers used perceived helpfulness to explain sales as well [@ghose2011; @lee2018]. Thus, these two branches are inter-connected with each other. This paper tries to understand behavioral aspect.

Many independent variables and their relationship between perceived helpfulness was examined by researchers. Hong et al. (2017) @hong2017 groups these independent variables into two chunks. The first group is reviewer-related predictors. Variables within this group tries to understand the relationship between reviewer status and perceived helpfulness(reviewer expertise, number of past reviews etc.). [@sun2019; @ghose2011]. The second group tries to understand the review-related relationships such as review length, review extremity, discrete review emotion etc [@mudambi2010; @ghose2011; @ren2019; @eslami2018]. Ghose et al. (2011) @ghose2011 showed that review-related predictors have stronger prediction power than reviewer-related ones. The choice of the variables is of course heavily dependent on the data itself. In this paper, we only examined review-related predictors.

Review Length(Depth) could be considered as one of the most important independent variable explaining perceived helpfulness. It might be implemented in different ways but for the majority of the studies it is the word count in a given review. For most of the researchers, longer reviews contain more information about the product. As the potential buyer gets more information from a single review, he decreases his search costs with minimum effort [@mudambi2010; @hong2017; @liu2014; @wang2018; @korfiatis2012; @lee2016; @lee2014; @choi2020]. However, other group of researchers found out that there was a threshold on review length, meaning longer reviews might have useless information in them[@schindler2012; @huang2015]. Another group indicates the word count of the review shows diminishing returns to helpfulness, supporting the threshold idea [@baek2012; @kuan2015; @eslami2018].

Review Rating (Review Extremity) is another important identifier of perceived helpfulness. This is usually the star rating on a 1-5 or 1-10 scale and resembles the evaluation of the reviewer for a given product. It's effect on perceived helpfulness is rather divergent in the literature. A number of researchers found out that there is a non-linear relationship between review extremity and perceived helpfulness. Specifically, a U-Shaped function which means that reviews that are on the extremes (either very negative or very positive) are more helpful than neutral reviews[@mudambi2010; @cao2011; @liu2014; @wang2018; @ghose2006]. In other studies, linear positive relationship was found. In other words, positively rated reviews are more useful [@pan2011; @schindler2012; @korfiatis2012; @lee2016; @choi2020]. There are also results that support negative linear relationship[@chua2014] and no effect at all[@hong2017].

Review Age is an indicator of how long the time passed after a review published on a web site. On some papers the opposite of Review Age, Review Freshness could be employed as well. Different effects on perceived helpfulness were also observed by researchers. Some researchers discussed that a timely review is very important at conveying the true information about a certain product [@liu2014; @li2019; @zhou2019]. Others discussed that some web sites promotes newer reviews and because of that more recent reviews are more helpful [@lee2014; @choi2020; @wu2021].

-   mention negative positive words here

# Theoretical Framework

## Search and Experience Goods Classification

-   extend this later and try to connect to the methodology

Nelson (1970) @10.2307/1830691 differentiated goods based on their search and experience attributes [@nelson1974economic; @nelson1974; @nelson1981]. Search Attributes are the qualities that can be assessed before purchase. On the contrary, Experience Attributes can only be assessed by using the product itself, in other words evaluation is only possible after purchase. A single good can have both search and experience attributes. Depending on its dominant attributes the good can be classified as Search or Experience. A product's Total Cost consists of both Search Cost and Product Cost. This Search Cost is higher for Experience Goods, in other words, information search is costlier for Experience Goods than Search Goods.

To explain it in a more generalized way, let's also define what "search" is. Nelson (1970) @10.2307/1830691 defines search as "The most obvious procedure available to the consumer in obtaining information about price or quality is search". People will always prefer sampling or trial use given the fact that the cost of the sampling or trial is lower than the cost of the search. This is why search is costlier for Experience Goods. For instance, getting information about a car (test drive, guides on the web etc.) is less costly than actually buying it. Even though a car has experience attributes, with this logic it is considered as a search good @klein1998.

-   might explain why negative reviews arent that helpful for movies

## Negativity Bias Theorem and Loss Aversion

-   needs to be connected to the method

Humans tend to care about losses more than same amount of gains. Losing 100\$ is psycholgically much more impactful than finding 100\$. This behavior is best explained by "loss aversion" from Behavioral Economics. [@kahneman1979; @schindler2017]. Loss Aversion has a strong connection to Negativity Bias Theorem since negative cues might be used as an early warning against potential losses @herr1991.

Negativity Bias Theorem has four main aspects, namely, higher negative potency -- Negative signals have more impact on people than positive ones. --, steeper negative gradients -- Negativity of negatives events grows faster in space and time than positive ones. --, higher negative dominance --
A combination of equally negative and positive cues results in more negative impressions. --, and various negative differentiations -- Negative cues produce more diverse individual responses than positive ones. --[ @rozin2001; @sen2007; @eslami2018].

-   Social Learning and Herding Effect

# Methodology

## Data Collection

## Variables and EDA

## Method

# Results

# Discussion and Conclusion

# References
